version: '3.8'

services:
  web:
    build: .
    command: poetry run uvicorn loan_calculator.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_URL=sqlite:///db.sqlite3
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=loan_calculator
      - POSTGRES_USER=loan_calculator_user
      - POSTGRES_PASSWORD=loan_calculator_password

volumes:
  postgres_data:
