version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=loan_calculator.settings

  nginx:
    image: nginx:alpine
    volumes:
      - ./loan-payment-calculator-frontend/dist:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - web
