version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      # Django admin is currently broken unless this is set to True, as I haven't configured the copying of static files into nginx
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=loan_calculator.settings
      - ALLOWED_HOSTS=localhost

  nginx:
    # Note: I should be building the nginx and copying loan-payment-calculator-frontend and django static files to the nginx container
    image: nginx:alpine
    volumes:
      - ./loan-payment-calculator-frontend/dist:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - web
