# Generated by Django 5.1.2 on 2024-10-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("down_payment", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "down_payment_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("amount", "Amount")],
                        max_length=10,
                    ),
                ),
                ("mortgage_term", models.IntegerField()),
                (
                    "term_type",
                    models.CharField(
                        choices=[("years", "Years"), ("months", "Months")],
                        max_length=10,
                    ),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "total_loan_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_amount_paid",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_interest_paid",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
